name: Build nulldce-psp

on:
  push:
    branches: ['*']
    tags: [v*]
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build in fjtrujy/pspdev container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            fjtrujy/pspdev \
            bash -c "cd psp && make clean && make"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EBOOT.PBP
          path: psp/EBOOT.PBP
