name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [fjtrujy/pspdev]

    container: ${{ matrix.docker_tag }}:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git bash cmake

    - name: Compile project
      run: |
        cd ./psp
        make clean
        make

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    
    - name: Sanitized Docker Tag
      id: docker_tag
      run: echo "sha8=$(echo ${{matrix.docker_tag}} | sed s:/:__:g)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: hello-${{ env.sha8 }}-${{ steps.docker_tag.outputs.sha8 }}
        path: |
          ./psp/EBOOT.PBP
