name: cl

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Show directory before build
        run: ls -al

      - name: Run build inside fjtrujy/pspdev
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work/psp \
            fjtrujy/pspdev \
            bash -c "make clean && make && ls -al"

      - name: Show directory after build
        run: ls -al ./psp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EBOOT.PBP
          path: psp/EBOOT.PBP
